# Generated by Django 4.0.1 on 2022-01-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('colored', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('black_white', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('colored_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('black_white_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
